project_id = "vderxlqqxmvnrdxwyogy"

[functions.chat]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.mp-webhook]
verify_jwt = false

[functions.analyze-edital]
verify_jwt = false

[functions.save-gateway-config]
verify_jwt = false

[functions.notebook-search]
verify_jwt = false

[functions.notebook-fetch]
verify_jwt = false

[functions.send-email]
verify_jwt = true

[functions.generate-document]
verify_jwt = true
